on:
  workflow_dispatch:
  push:
    branches: [main]

name: release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: extractions/setup-just@v1
        if: ${{ steps.release.outputs.release_created }}

      - run: |
          curl https://github.com/catppuccin/toolbox/releases/download/whiskers-v1.1.4/whiskers-x86_64-unknown-linux-gnu -o $RUNNER_TEMP/whiskers
          chmod +x $RUNNER_TEMP/whiskers
          echo $RUNNER_TEMP >> $GITHUB_PATH
        if: ${{ steps.release.outputs.release_created }}

      - run: just all
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.release.outputs.release_created }}
        with:
          message: "chore: release (${{ steps.release.outputs.tag_name }})"
          default_author: github_actions
